name: Test deploy

# Deploy on main update
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      GANDI_ID: 4748832
      GANDI_HOST: git.sd5.gpaas.net
      # to be replaced with the real projects home directory on Gandi, like [vhosts/]oe.cd[/htdocs]
      GANDI_REPO: 8f70018c4bab4ed3a3cf2a23224dde85.testmyurl.ws
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out main
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        ref: 'main'
    - run: |
        echo "DB_USER={{ secrets.DB_USER }}" >> .env
        echo "DB_PASS={{ secrets.DB_PASS }}" >> .env
        echo "DB_NAME={{ secrets.DB_NAME }}" >> .env
        echo "DB_HOST={{ secrets.DB_HOST }}" >> .env
        echo "DB_PREFIX={{ secrets.DB_PREFIX }}" >> .env
        echo "SITE={{ secrets.SITE_OECD_IO }}" >> .env
        echo "COOKIEKEY={{ secrets.COOKIEKEY }}" >> .env
        echo "FLOOD_IP_WHITELIST={{ secrets.FLOOD_IP_WHITELIST }}" >> .env
        echo "ADMIN_USER={{ secrets.ADMIN_USER }}" >> .env
        echo "ADMIN_PASS={{ secrets.ADMIN_PASS }}" >> .env
        echo "AUTH_IPS={{ secrets.AUTH_IPS }}" >> .env

    # install SSH key
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         known_hosts: ${{ secrets.KNOWN_HOSTS_SD5 }}

    # set Git config
    - run: git config --global user.email "jakob.fix@gmail.com"
    - run: git config --global user.name "Jakob Fix"

    # Add Gandi remote and push
    - run: git remote add gandi git+ssh://${{ env.GANDI_ID }}@${{ env.GANDI_HOST }}/${{ env.GANDI_REPO }}.git
    - run: git push -v gandi main -f

    # Runs SSH Clean on Gandi
    - name: Run SSH clean
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: clean ${{ env.GANDI_REPO }}.git
        host: ${{ env.GANDI_HOST }}
        username: ${{ env.GANDI_ID }}
        privateKey: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy .env to remote server
      uses: Creepios/sftp-action@v1.0.1
      with:
        host: ${{ env.GANDI_HOST }}
        port: 22
        username: ${{ env.GANDI_ID }}
        privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
        localPath: '.env'
        remotePath: './vhosts/${{ env.GANDI_REPO }}/.env'

    # Runs SSH Deploy on Gandi
    - name: Run SSH deploy
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: deploy ${{ env.GANDI_REPO }}.git main
        host: ${{ env.GANDI_HOST }}
        username: ${{ env.GANDI_ID }}
        privateKey: ${{ secrets.SSH_PRIVATE_KEY }}